allowBuilds:
  '@parcel/watcher': false
  dprint: false
  esbuild: false
  svelte-preprocess: false
  unrs-resolver: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - dprint
  - esbuild
  - svelte-preprocess

patchedDependencies:
  '@excalidraw/excalidraw': patches/@excalidraw__excalidraw.patch
